name: Build check
env:
  NODE_VERSION: 21.7.3
  PNPM_VERSION: 10.2.0
  BIOME_VERSION: 1.9.3
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - name: Install pnpm
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Store build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
      - name: Start
        run: pnpm start

  biome-lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: ${{ env.BIOME_VERSION }}
      - name: Run Biome
        run: biome ci .